language: java

jdk:
  - openjdk8

install:
  - ./gradlew setupCiWorkspace

script:
  - ./gradlew build

before_deploy:
  - .travis/before_deploy.sh

deploy:
  - provider: pages
    github-token: $GITHUB_TOKEN
    email: liaoyuan@gmail.com
    name: Leo
    local-dir: .travis/pages
    skip_cleanup: true
    on:
      tags: true
  - provider: releases
    api_key: $GITHUB_TOKEN
    file_glob: true # Enables wildcard
    file: build/libs/*
    skip_cleanup: true
    on:
      tags: true
